### ISSUE TITLE
Add some basic configurations to the examples

### ISSUE THREAD

**Issue by buddha314** [budparr/gohugo-theme-ananke#114]
In looking through the theme, here are a few things I don't yet know how to do.  Keep in mind that I am very new to static web site builders, so what is obvious to others may not be to me.

1. Add an "Author" and a date to a post
1. Add an "email" to the footer.
1. Add the smaller image next to the post title like in your example.  Where does that go?
1. Add the navigation, About, Authors, etc to the hero unit.  Though I got github.

I'll probably think of more as I play with it. Thanks so much for the theme!

**Comment by veenavijai** [comment]
For 1 and 7, you can add this to the start of each .md file:
date: 2021-02-03
tags: ["A", "B", "C"]

**Comment by melroy89** [comment]
You should be able to do this as well for tags & categories at the top of your markdown file, an example:

```yaml
---
title: Post title example
author: Melroy van den Berg
type: post
date: 2023-11-30T00:00:00+00:00
categories:
  - Server
  - Linux
tags:
  - Linux
  - GNU
  - bash
---
```
