### ISSUE TITLE
Increasing the width of articles and justifying the text

### ISSUE THREAD

**Issue by prdm0** [budparr/gohugo-theme-ananke#288]
Hello, first congratulations on the theme. It is a clean and elegant theme. I am implementing the site https://prdm0.rbind.io/ and I have three questions:

1 - Is there any way to increase the width of the articles in order to allow longer sentences? How would it be?

2 - Is there any way to justify the texts? How would it be?

3 - I noticed that the images on my site warp a little when I see it on the smartphone. Is there anything I can modify to make it fit better?

Best regards,

**Comment by prdm0** [comment]
I managed to solve items 2 and 3. I did it in **custom.css** in `/static/css/custom.css`:

```css
.cf {
  text-align: justify;
  opacity: 1.0;
  width: 100%;
  height: auto;
}

img {
  max-width: 100%;
  height: auto;
}

video {
  width: 100%;
  height: auto;
}
```
I still have doubts on how to solve item 1. I want to adjust the width of the posts.

Thank you.
