### ISSUE TITLE
Header menu - weighting of different pages

### ISSUE THREAD

**Issue by willwade** [budparr/gohugo-theme-ananke#89]
Is there a way (maybe via frontmatter) of changing the order of the menu items rather than being alphabetic?

**Comment by budparr** [comment]
Yeah, it's actually pretty easy. Hugo's organizing principle is `weight` first, and then, I believe, in absence of weight, use alpha. 

So, to rearrange the menu, you'd first want to 

- [ ] Remove `SectionPagesMenu = "main"` from your config, if it's there.
- [ ] Create a new menu either in config or in your pages (this is pretty simple, but check the docs), including the weight parameter. Make sure the menu you create is called `main`.

That's it! I'll leave this open, if you don't mind letting me know how it worked out for you (i.e. if it's as easy I say).

**Comment by willwade** [comment]
Got you. The bit in the docs for anyone else following this: https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu

**Comment by javigomez** [comment]
I overwrote `/layouts/partials/site-navigation.html` layout this way:

before:
`{{ range .Site.Menus.main }}`

after:
` {{ range sort .Site.Menus.main "Weight" }}`


Then make sure you add weight to your menu. Should look something like:

```yaml
languages:
  en:
    title: test…
    languageName: English
    weight: 1
    contentDir: content/
    menu:
      main:
        - name: home
          url: /
          weight: 0
        - name: project
          url: /project
          weight: 1
        - name: vision
          url: /vision
          weight: 2
```
